/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 */
public class Mainpage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    static String movie = "";
    static String time = "";
    static String date = "";

    public Mainpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieButtons = new javax.swing.ButtonGroup();
        guardianTimeButtons = new javax.swing.ButtonGroup();
        dunkirkTimeButtons = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        johnWickTimeButtons = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        johnWickPicture = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        goTGPicture = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dunkirkPicture = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        guardiansRadioButton = new javax.swing.JRadioButton();
        dunkirkRadioButton = new javax.swing.JRadioButton();
        johnWickRadioButton = new javax.swing.JRadioButton();
        guardiansTimes = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        guardiansTime1 = new javax.swing.JRadioButton();
        guardiansTime2 = new javax.swing.JRadioButton();
        guardiansTime3 = new javax.swing.JRadioButton();
        guardiansTime4 = new javax.swing.JRadioButton();
        guardiansTime5 = new javax.swing.JRadioButton();
        guardiansTime6 = new javax.swing.JRadioButton();
        guardiansTime7 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        dunkirkTime1 = new javax.swing.JRadioButton();
        dunkirkTime2 = new javax.swing.JRadioButton();
        dunkirkTime3 = new javax.swing.JRadioButton();
        dunkirkTime4 = new javax.swing.JRadioButton();
        dunkirkTime5 = new javax.swing.JRadioButton();
        dunkirkTime6 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        johnWickTime1 = new javax.swing.JRadioButton();
        johnWickTime2 = new javax.swing.JRadioButton();
        johnWickTime3 = new javax.swing.JRadioButton();
        johnWickTime4 = new javax.swing.JRadioButton();
        johnWickTime5 = new javax.swing.JRadioButton();
        johnWickTime6 = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();
        dateComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        johnWickPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/johnwick.jpg"))); // NOI18N
        johnWickPicture.setToolTipText("John Wick");
        johnWickPicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        johnWickPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                johnWickPictureMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("John Wick");
        jLabel3.setToolTipText("John Wick");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Guardians of the Galaxy");
        jLabel4.setToolTipText("Guardians of the Galaxy");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 17));

        goTGPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goTGPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guardians1.jpg"))); // NOI18N
        goTGPicture.setToolTipText("Guardians of the Galaxy");
        goTGPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goTGPictureMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Dunkirk");
        jLabel6.setToolTipText("Dunkirk");

        dunkirkPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dunkirk.jpg"))); // NOI18N
        dunkirkPicture.setToolTipText("Dunkirk");
        dunkirkPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dunkirkPictureMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(johnWickPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goTGPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(dunkirkPicture))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(johnWickPicture)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goTGPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dunkirkPicture)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Top Movies");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        movieButtons.add(guardiansRadioButton);
        guardiansRadioButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        guardiansRadioButton.setText("Guardians of the Galaxy (pg-13)");
        guardiansRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardiansRadioButtonActionPerformed(evt);
            }
        });

        movieButtons.add(dunkirkRadioButton);
        dunkirkRadioButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dunkirkRadioButton.setText("Dunkirk (pg-13)");
        dunkirkRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dunkirkRadioButtonActionPerformed(evt);
            }
        });

        movieButtons.add(johnWickRadioButton);
        johnWickRadioButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        johnWickRadioButton.setText("John Wick (R)");
        johnWickRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                johnWickRadioButtonActionPerformed(evt);
            }
        });

        guardiansTimes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        guardiansTimes.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        guardiansTimes.setMaximumSize(new java.awt.Dimension(42, 575));
        guardiansTimes.setMinimumSize(new java.awt.Dimension(42, 575));

        guardianTimeButtons.add(guardiansTime1);
        guardiansTime1.setText("10:00 am");
        guardiansTime1.setEnabled(false);
        guardiansTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardiansTime1ActionPerformed(evt);
            }
        });

        guardianTimeButtons.add(guardiansTime2);
        guardiansTime2.setText("12:15 PM");
        guardiansTime2.setEnabled(false);

        guardianTimeButtons.add(guardiansTime3);
        guardiansTime3.setText("2:45 PM");
        guardiansTime3.setEnabled(false);

        guardianTimeButtons.add(guardiansTime4);
        guardiansTime4.setText("4:50 PM");
        guardiansTime4.setEnabled(false);

        guardianTimeButtons.add(guardiansTime5);
        guardiansTime5.setText("7:15 PM");
        guardiansTime5.setEnabled(false);

        guardianTimeButtons.add(guardiansTime6);
        guardiansTime6.setText("9:30 PM");
        guardiansTime6.setToolTipText("");
        guardiansTime6.setEnabled(false);
        guardiansTime6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardiansTime6ActionPerformed(evt);
            }
        });

        guardianTimeButtons.add(guardiansTime7);
        guardiansTime7.setText("10:45 PM");
        guardiansTime7.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(guardiansTime1)
                .addGap(50, 50, 50)
                .addComponent(guardiansTime2)
                .addGap(50, 50, 50)
                .addComponent(guardiansTime3)
                .addGap(50, 50, 50)
                .addComponent(guardiansTime4)
                .addGap(50, 50, 50)
                .addComponent(guardiansTime5)
                .addGap(50, 50, 50)
                .addComponent(guardiansTime6)
                .addGap(50, 50, 50)
                .addComponent(guardiansTime7)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardiansTime1)
                    .addComponent(guardiansTime2)
                    .addComponent(guardiansTime3)
                    .addComponent(guardiansTime4)
                    .addComponent(guardiansTime5)
                    .addComponent(guardiansTime6)
                    .addComponent(guardiansTime7))
                .addGap(0, 77, Short.MAX_VALUE))
        );

        guardiansTimes.setViewportView(jPanel3);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setMaximumSize(new java.awt.Dimension(42, 575));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(42, 575));

        dunkirkTimeButtons.add(dunkirkTime1);
        dunkirkTime1.setText("11:15 AM");
        dunkirkTime1.setEnabled(false);

        dunkirkTimeButtons.add(dunkirkTime2);
        dunkirkTime2.setText("1:45 PM");
        dunkirkTime2.setEnabled(false);

        dunkirkTimeButtons.add(dunkirkTime3);
        dunkirkTime3.setText("3:50 PM");
        dunkirkTime3.setEnabled(false);
        dunkirkTime3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dunkirkTime3ActionPerformed(evt);
            }
        });

        dunkirkTimeButtons.add(dunkirkTime4);
        dunkirkTime4.setText("5:25 PM");
        dunkirkTime4.setEnabled(false);
        dunkirkTime4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dunkirkTime4ActionPerformed(evt);
            }
        });

        dunkirkTime5.setText("8:00 PM");
        dunkirkTime5.setEnabled(false);
        dunkirkTime5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dunkirkTime5ActionPerformed(evt);
            }
        });

        dunkirkTime6.setText("10:15 PM");
        dunkirkTime6.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(dunkirkTime1)
                .addGap(50, 50, 50)
                .addComponent(dunkirkTime2)
                .addGap(50, 50, 50)
                .addComponent(dunkirkTime3)
                .addGap(50, 50, 50)
                .addComponent(dunkirkTime4)
                .addGap(50, 50, 50)
                .addComponent(dunkirkTime5)
                .addGap(50, 50, 50)
                .addComponent(dunkirkTime6)
                .addGap(0, 582, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dunkirkTime1)
                    .addComponent(dunkirkTime2)
                    .addComponent(dunkirkTime3)
                    .addComponent(dunkirkTime4)
                    .addComponent(dunkirkTime5)
                    .addComponent(dunkirkTime6))
                .addGap(0, 77, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel5);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setMaximumSize(new java.awt.Dimension(42, 575));
        jScrollPane4.setMinimumSize(new java.awt.Dimension(42, 575));

        johnWickTimeButtons.add(johnWickTime1);
        johnWickTime1.setText("10:30 AM");
        johnWickTime1.setEnabled(false);
        johnWickTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                johnWickTime1ActionPerformed(evt);
            }
        });

        johnWickTimeButtons.add(johnWickTime2);
        johnWickTime2.setText("12:05 PM");
        johnWickTime2.setEnabled(false);

        johnWickTimeButtons.add(johnWickTime3);
        johnWickTime3.setText("1:45 PM");
        johnWickTime3.setEnabled(false);

        johnWickTimeButtons.add(johnWickTime4);
        johnWickTime4.setText("4:50 PM");
        johnWickTime4.setEnabled(false);

        johnWickTimeButtons.add(johnWickTime5);
        johnWickTime5.setText("7:50 PM");
        johnWickTime5.setEnabled(false);

        johnWickTimeButtons.add(johnWickTime6);
        johnWickTime6.setText("10:00 PM");
        johnWickTime6.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(johnWickTime1)
                .addGap(50, 50, 50)
                .addComponent(johnWickTime2)
                .addGap(50, 50, 50)
                .addComponent(johnWickTime3)
                .addGap(50, 50, 50)
                .addComponent(johnWickTime4)
                .addGap(50, 50, 50)
                .addComponent(johnWickTime5)
                .addGap(50, 50, 50)
                .addComponent(johnWickTime6)
                .addGap(0, 329, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(johnWickTime1)
                    .addComponent(johnWickTime2)
                    .addComponent(johnWickTime3)
                    .addComponent(johnWickTime4)
                    .addComponent(johnWickTime5)
                    .addComponent(johnWickTime6))
                .addGap(0, 77, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardiansRadioButton)
                            .addComponent(dunkirkRadioButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(johnWickRadioButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guardiansTimes, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(701, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guardiansRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardiansTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(dunkirkRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(johnWickRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        jScrollPane5.setViewportView(jPanel7);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Welcome to Zee Movies");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3/26/18", "3/27/18", "3/28/18", "3/30/18" }));

        jLabel5.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(continueButton)
                                .addGap(18, 18, 18)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(161, 161, 161))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton)
                            .addComponent(continueButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void johnWickPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_johnWickPictureMouseClicked
        new JohnWick().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_johnWickPictureMouseClicked

    private void guardiansRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardiansRadioButtonActionPerformed
        guardiansTime1.setEnabled(true);
        guardiansTime2.setEnabled(true);
        guardiansTime3.setEnabled(true);
        guardiansTime4.setEnabled(true);
        guardiansTime5.setEnabled(true);
        guardiansTime6.setEnabled(true);
        guardiansTime7.setEnabled(true);
        johnWickTime1.setEnabled(false);
        johnWickTime2.setEnabled(false);
        johnWickTime3.setEnabled(false);
        johnWickTime4.setEnabled(false);
        johnWickTime5.setEnabled(false);
        johnWickTime6.setEnabled(false);
        dunkirkTime1.setEnabled(false);
        dunkirkTime2.setEnabled(false);
        dunkirkTime3.setEnabled(false);
        dunkirkTime4.setEnabled(false);
        dunkirkTime5.setEnabled(false);
        dunkirkTime6.setEnabled(false);
        dunkirkTimeButtons.clearSelection();
        johnWickTimeButtons.clearSelection();
    }//GEN-LAST:event_guardiansRadioButtonActionPerformed

    private void guardiansTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardiansTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardiansTime1ActionPerformed

    private void guardiansTime6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardiansTime6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardiansTime6ActionPerformed

    private void dunkirkTime3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dunkirkTime3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dunkirkTime3ActionPerformed

    private void dunkirkTime4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dunkirkTime4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dunkirkTime4ActionPerformed

    private void dunkirkTime5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dunkirkTime5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dunkirkTime5ActionPerformed

    private void johnWickTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_johnWickTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_johnWickTime1ActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        if (guardiansRadioButton.isSelected()) {
            movie = "Guardians of the Galaxy";
            date = (String) dateComboBox.getSelectedItem();
            if (guardiansTime1.isSelected()) {
                time = "10:00 AM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (guardiansTime2.isSelected()) {
                time = "12:15 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (guardiansTime3.isSelected()) {
                time = "2:45 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (guardiansTime4.isSelected()) {
                time = "4:50 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (guardiansTime5.isSelected()) {
                time = "7:15 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (guardiansTime6.isSelected()) {
                time = "9:30 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (guardiansTime7.isSelected()) {
                time = "10:45 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else {
                Component frame = null;
                JOptionPane.showMessageDialog(frame, "You must select a time.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else if (dunkirkRadioButton.isSelected()) {
            movie = "Dunkirk";
            date = (String) dateComboBox.getSelectedItem();
            if (dunkirkTime1.isSelected()) {
                time = "11:15 AM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (dunkirkTime2.isSelected()) {
                time = "1:45 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (dunkirkTime3.isSelected()) {
                time = "3:50 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (dunkirkTime4.isSelected()) {
                time = "5:25 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (dunkirkTime5.isSelected()) {
                time = "8:00 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (dunkirkTime6.isSelected()) {
                time = "10:15 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else {
                Component frame = null;
                JOptionPane.showMessageDialog(frame, "You must select a time.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else if (johnWickRadioButton.isSelected()) {
            movie = "John Wick";
            date = (String) dateComboBox.getSelectedItem();
            if (johnWickTime1.isSelected()) {
                time = "10:30 AM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (johnWickTime2.isSelected()) {
                time = "12:05 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (johnWickTime3.isSelected()) {
                time = "2:45 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (johnWickTime4.isSelected()) {
                time = "4:50 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (johnWickTime5.isSelected()) {
                time = "7:50 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else if (johnWickTime6.isSelected()) {
                time = "10:00 PM";
                this.setVisible(false);
                new TicketSelector().setVisible(true);
            } else {
                Component frame = null;
                JOptionPane.showMessageDialog(frame, "You must select a time.", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "You must select a movie.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void dunkirkRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dunkirkRadioButtonActionPerformed
        guardiansTime1.setEnabled(false);
        guardiansTime2.setEnabled(false);
        guardiansTime3.setEnabled(false);
        guardiansTime4.setEnabled(false);
        guardiansTime5.setEnabled(false);
        guardiansTime6.setEnabled(false);
        guardiansTime7.setEnabled(false);
        johnWickTime1.setEnabled(false);
        johnWickTime2.setEnabled(false);
        johnWickTime3.setEnabled(false);
        johnWickTime4.setEnabled(false);
        johnWickTime5.setEnabled(false);
        johnWickTime6.setEnabled(false);
        dunkirkTime1.setEnabled(true);
        dunkirkTime2.setEnabled(true);
        dunkirkTime3.setEnabled(true);
        dunkirkTime4.setEnabled(true);
        dunkirkTime5.setEnabled(true);
        dunkirkTime6.setEnabled(true);
        johnWickTimeButtons.clearSelection();
        guardianTimeButtons.clearSelection();
    }//GEN-LAST:event_dunkirkRadioButtonActionPerformed

    private void johnWickRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_johnWickRadioButtonActionPerformed
        guardiansTime1.setEnabled(false);
        guardiansTime2.setEnabled(false);
        guardiansTime3.setEnabled(false);
        guardiansTime4.setEnabled(false);
        guardiansTime5.setEnabled(false);
        guardiansTime6.setEnabled(false);
        guardiansTime7.setEnabled(false);
        johnWickTime1.setEnabled(true);
        johnWickTime2.setEnabled(true);
        johnWickTime3.setEnabled(true);
        johnWickTime4.setEnabled(true);
        johnWickTime5.setEnabled(true);
        johnWickTime6.setEnabled(true);
        dunkirkTime1.setEnabled(false);
        dunkirkTime2.setEnabled(false);
        dunkirkTime3.setEnabled(false);
        dunkirkTime4.setEnabled(false);
        dunkirkTime5.setEnabled(false);
        dunkirkTime6.setEnabled(false);
        dunkirkTimeButtons.clearSelection();
        guardianTimeButtons.clearSelection();
    }//GEN-LAST:event_johnWickRadioButtonActionPerformed

    private void goTGPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goTGPictureMouseClicked
        new Guardians().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goTGPictureMouseClicked

    private void dunkirkPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dunkirkPictureMouseClicked
        new Dunkirk().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_dunkirkPictureMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JLabel dunkirkPicture;
    private javax.swing.JRadioButton dunkirkRadioButton;
    private javax.swing.JRadioButton dunkirkTime1;
    private javax.swing.JRadioButton dunkirkTime2;
    private javax.swing.JRadioButton dunkirkTime3;
    private javax.swing.JRadioButton dunkirkTime4;
    private javax.swing.JRadioButton dunkirkTime5;
    private javax.swing.JRadioButton dunkirkTime6;
    private javax.swing.ButtonGroup dunkirkTimeButtons;
    private javax.swing.JLabel goTGPicture;
    private javax.swing.ButtonGroup guardianTimeButtons;
    private javax.swing.JRadioButton guardiansRadioButton;
    private javax.swing.JRadioButton guardiansTime1;
    private javax.swing.JRadioButton guardiansTime2;
    private javax.swing.JRadioButton guardiansTime3;
    private javax.swing.JRadioButton guardiansTime4;
    private javax.swing.JRadioButton guardiansTime5;
    private javax.swing.JRadioButton guardiansTime6;
    private javax.swing.JRadioButton guardiansTime7;
    private javax.swing.JScrollPane guardiansTimes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel johnWickPicture;
    private javax.swing.JRadioButton johnWickRadioButton;
    private javax.swing.JRadioButton johnWickTime1;
    private javax.swing.JRadioButton johnWickTime2;
    private javax.swing.JRadioButton johnWickTime3;
    private javax.swing.JRadioButton johnWickTime4;
    private javax.swing.JRadioButton johnWickTime5;
    private javax.swing.JRadioButton johnWickTime6;
    private javax.swing.ButtonGroup johnWickTimeButtons;
    private javax.swing.ButtonGroup movieButtons;
    // End of variables declaration//GEN-END:variables
}
